### ISSUE TITLE
Score not lining up: issues with mensuration encoding

### ISSUE THREAD

**Issue by martha-thomae** [HISPAMUS/muret#102]
**Describe the bug**
There are two issues with the encoding of the mensuration that are affecting the lining up of the voices even when the semantic encoding is perfect. The issues are:

1. The attributes `@modusmaior` and `@modusminor` also need to be included within the `<staffDef>` element. If a piece in imperfect mensuration does not include the `@modusmaior="2"` and `@modusminor="2"`, when a `longa` or a `maxima` appear, the alignment of the notes messes up (because Verovio gives them a perfect value by default).

2. The `<mensur>` elements should be removed from the `<score>` representation (not from the `<parts>` one). Each new `<mensur>` element resets the mensuration back to its default values (which makes all the notes perfect).
 
**Screenshots**
This is how the _7 MISSA SINE NOMINE_ looks like when rendering the full score. These are the first double barlines in the pages 31v and 32r. They should line up, but they don't. When making the two corrections indicated above (and nothing else), the piece lines up when rendered in Verovio.

I am attaching here the original file retrieved from MuRET (which renders in Verovio just as shown in the image) and the modified one (with the issues corrected). In the modified one, I just added `@modusminor="2"` and not the `@modusmaior="2"`. This is because I knew there were no maximas in the music; but if a maxima appeared, the lining up of the notes would be messed up due to the missing `@modusmaior="2"` definition.
 
![current_alignment_in_mei_visualization](https://user-images.githubusercontent.com/13948831/71786245-665bfc80-2fd7-11ea-9ce8-e02a15d0e6a3.png)

[7_MISSA_SINE_NOMINE_Kyrie.zip](https://github.com/HISPAMUS/muret/files/4024070/7_MISSA_SINE_NOMINE_Kyrie.zip)

**Comment by davidrizo** [comment]
Solved just waiting for adding the correct modusmaior and modusminor for all mensurations
