### ISSUE TITLE
Semantic: mensuration sign does not get encoded when appearing in the middle of the staff

### ISSUE THREAD

**Issue by martha-thomae** [HISPAMUS/muret#103]
**Describe the bug**
When there is a mensuration sign in the middle of the staff, it causes problems in the semantic encoding. Even though the sign is contained in the agnostic encoding, it causes problems when clicking on "convert from agnostic," see screenshots.

**Expected behavior**
The mensuration sign gets encoded as `*met(C)` (or whatever the sign is) in the correct index.

**Screenshots**
Example in file 36v, 3rd staff (this can be found in the folder "7 MISSA SINE NOMINE" in the Guatemalan Manuscript).
![Menusration sign isue - 36v, staff 3](https://user-images.githubusercontent.com/13948831/71786782-ae7e1d80-2fdd-11ea-9a45-fbc6709763c6.png)

Same page, other mensuration sign (staff 2)
![36v, staff 2](https://user-images.githubusercontent.com/13948831/71786784-bb027600-2fdd-11ea-81fe-55f5ae98256e.png)

**Comment by davidrizo** [comment]
The MEI export of mensur element has also been corrected for *met(C|3/2)
