### ISSUE TITLE
Semantic to MEI: Missing the encoding of perfections / imperfections / alterations

### ISSUE THREAD

**Issue by martha-thomae** [HISPAMUS/muret#108]
### Is your feature request related to a problem? Please describe.
When using *mens grammar to include perfections (`p`), imperfections (`i`), and alterations (`I`) in the semantic encoding, these do not get translated into any MEI attributes.

### Describe the solution you'd like

- Imperfect notes must be translated into `dur.quality="i"`. In addition, one needs to include the `@num` and `@numbase` pairs of attributes for now: `num="3" numbase="2"`.
- Altered notes must be translated into `dur.quality="a"`. In addition, one needs to include the `@num` and `@numbase` pairs of attributes for now: `num="1" numbase="2"`.
- Perfect notes must be translated into `dur.quality="p"`. (This doesn't need any extra `@num` and `@numbase` attributes because we are in a triple meter section, so by default the note is interpreted as perfect---as the mensuration indicates---only imperfections and alterations imply a deviation from the default mensuration value and, therefore, require the pair of `@num` and `@numbase` attributes).

The `@num` and `@numbase` pairs of attributes will be eliminated in a future version of MEI (currently waiting for approval). If this pairs of attributes are not included, the music won't render correctly in Verovio and won't be consistent with the current specification of MEI.

### Additional Context (Examples)
In _7 MISSA SINE NOMINE_ there are triple meter sections (which require the use of imperfect and perfect annotations in the semantic encoding) in pages _36v_ (staves 2–3 and 8–9) and _37r_ (staves 2–3 and 7–8). 

### Specific Example
Look at _2nd staff_ of _36v_ in _7 MISSA SINE NOMINE_

After the mensuration change we have:
```
<mensur sign="C" num="3" numbase="2" slash="1" modusmaior="2" modusminor="2" tempus="3" prolatio="2"/>
<note xml:id="A19" dur="brevis" pname="d" oct="4"/>
<rest xml:id="A20" dur="longa" loc="4"/>
<rest xml:id="A21" dur="longa" loc="4"/>
<note xml:id="A22" dur="brevis" pname="g" oct="4"/>
<note xml:id="A23" dur="semibrevis" pname="a" oct="4"/>
<custos pname="b" oct="4"/>
```

Should be:
```
<mensur sign="C" num="3" numbase="2" slash="1" modusmaior="2" modusminor="2" tempus="3" prolatio="2"/>
<note xml:id="A19" dur="brevis" pname="d" oct="4" dur.quality="p"/>
<rest xml:id="A20" dur="longa" loc="4"/>
<rest xml:id="A21" dur="longa" loc="4"/>
<note xml:id="A22" dur="brevis" pname="g" oct="4" dur.quality="i" num="3" numbase="2"/>
<note xml:id="A23" dur="semibrevis" pname="a" oct="4"/>
<custos pname="b" oct="4"/>
```

**The difference is in the two breves**. The first one is perfect (so I added `dur.quality="p"`) and the second one is imperfect (so I added `dur.quality="i" num="3" numbase="2"`).

### Extra examples just to test
Look at _staff 8_ in _37r_ of (again) _7 MISSA SINE NOMINE_

We have`[Si~D Si~E]` a ligature made up of two imperfect colored breves which should be encoded as:
```
<ligature>
    <note pname="d" oct="3" dur="brevis" colored="true" dur.quality="i" num="3" numbase="2" />
    <note pname="e" oct="3" dur="brevis" colored="true" dur.quality="i" num="3" numbase="2" />
</ligature>
```
Right now it is just not translating any of the staff into MEI.

Look at _staff 7_ in _37r_ of (again) _7 MISSA SINE NOMINE_ where we have `Sp:D`, which represents a perfect breve (in D3) followed by a dot of division. Right now that note is encoded as:

```
<note xml:id="A26" dur="brevis" pname="d" oct="3"/>
<dot form="div"/>
```
It is just missing the `@dur.quality="p"`

**Comment by davidrizo** [comment]
It was not implemented in the IMCore to MEI exported.
Just one slight change in the **mens encoding:

- the encoding of coloration and perfection must follow this order:
S~iE
rather than
Si~E
