### ISSUE TITLE
Edits cause unselected bounding boxes to reappear on the image

### ISSUE THREAD

**Issue by martha-thomae** [HISPAMUS/muret#12]
**In Document Analysis:**
When I click on "View" to be able to see only the bounding boxes I am interested in (e.g., the staff ones), if I edit one of them (e.g., click on "Edit" and resize one bounding box) then all the bounding boxes reappear.

Here I attach a screenshot illustrating this behavior. After editing one of the staff bounding boxes, all bounding boxes reappear (see screenshot where lyrics, page, and staff bounding boxes are present, even though the only one type of bounding box that appears as selected on top is the one corresponding to staff).

**To Reproduce**
1. Click on view and only select one type of bounding box (e.g., staff)
2. Click on edit
3. Resize one of the (staff) bounding boxes
4. See how all bounding boxes reappear on the page
5. Click on view and see how only the originally selected bounding-box type (staff) is the only one selected even though all types are present in the image now.

![View_see_selected_filters_vs_displayed_boxes](https://user-images.githubusercontent.com/13948831/59592614-aff30180-90f0-11e9-8cd0-510774fecd9b.png)

**Comment by davidrizo** [comment]
Corrected
