### ISSUE TITLE
Missing sign for proportio tripla

### ISSUE THREAD

**Issue by martha-thomae** [HISPAMUS/muret#13]
Missing sign for proportio tripla when only the number "3"  appears (it is not included in the "clefs meters"). I don't know whether a separate category for proportions should be created for numbers or ratios that appear in the middle of the piece instead of appearing as some kind of "time signature" at the beginning of the voice.

![Missing proportion sign (3)](https://user-images.githubusercontent.com/13948831/59614341-de88d080-9120-11e9-9547-77e83358462e.png)

**Comment by davidrizo** [comment]
In agnostic they will be tagged as a digit. Currently MuRET is not allowing this tag. I'll include it.

**Comment by martha-thomae** [comment]
Thank you, David!

**Comment by davidrizo** [comment]
Digits added in "other" tab
