### ISSUE TITLE
Add spinner to all operations

### ISSUE THREAD

**Issue by davidrizo** [HISPAMUS/muret#132]
Add a spinner to all long lasting operations. See DocumentScoreViewerAndExporterComponent as example (note that there the boolean value that indicates that there is an ongoing operation is contained in a map because there are several operations that share the same behaviour)

**Comment by antoniorv6** [comment]
Implemented it in Agnostic analysis and Document Analysis. I will implement it in semantic conversion (I get an error but it's fine, i can do it anyway)
