### ISSUE TITLE
Jackson fails in document analysis

### ISSUE THREAD

**Issue by antoniorv6** [HISPAMUS/muret#135]
Testing the automatic document analysis model, i saw that the controller didn't trigger any exception. It is weird, but as the trace says, it may seem that it is Jackson JSON parser who is provoking it.
Internal Server Error
Could not write JSON: (was java.lang.NullPointerException); nested exception is com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: java.util.ArrayList[0]->es.ua.dlsi.grfia.im3ws.muret.entity.Page["regions"]->org.hibernate.collection.internal.PersistentBag[0]->es.ua.dlsi.grfia.im3ws.muret.entity.Region["sortedSymbols"])

**Comment by antoniorv6** [comment]
So, i have seen that it doesn't fail at all. It is weird because if you refresh de page, you get the result you have requested in the first instance, so the analysis is being performed well, but something wrong is going on when sending the first result to the client.

**Comment by davidrizo** [comment]
Solved adding @JsonIgnore to @Transient properties (such as the new getSortedSymbols()) that should not been included in the JSON serializing
