### ISSUE TITLE
Add training set generation from ground-truth

### ISSUE THREAD

**Issue by pierre-dlsi** [HISPAMUS/muret#137]
It would be helpful to streamline the training set generation process: select a corpus of images + corresponding JSON files, then generate images for staffs, symbols, etc, in order to train/test models.

Include a feature in Muret that, given a set of annotated documents, and a set of symbols you are interested in, returns a collection of cropped images extracted from those documents.

For example, suppose we are interested in obtaining cropped images of symbols from the Zaragoza corpus. We would select that corpus, then provide a list of agnostic symbol prefixes we are interested in, like `clef,metersign`, `note,rest`, `note.longa,rest.longa`, `ligature`, or `all` (for all agnostic symbols).

An option for extracting staffs would may be also helpful.

The resulting training set would be organized in folders as in the original corpus, plus subfolders for each type of extracted symbol. For example, given the Guatemala corpus, ligatures extracted from document '_106v_' in work '_12-missa-ave-maris-stella' would be in folder_ would be stored in a folder path like `guatemala/12-missa-ave-maris-stella/masters/106v/ligature/`.

**Comment by davidrizo** [comment]
Discarded. The [script respository](https://github.com/HISPAMUS/scripts) should be used to upload those scripts to extract information
