### ISSUE TITLE
Document analysis preview

### ISSUE THREAD

**Issue by fjcastellanos** [HISPAMUS/muret#143]
When you are labeling the document analysis information in the pages of a collection, you must click in the document analysis option to check if the page is not labeled. If you confirm that the page is already labeled, you can go back to the collection to search another unlabeled page, but you have to search manually page to page...

It could be interesting to add document analysis information when you click the image and a expanded preview appears on the screen. Maybe with a optional check to add this extra information if it is required.

**Comment by davidrizo** [comment]
Now the status of the document analysis can be changed to “working” or “done” to keep track of the progress
