### ISSUE TITLE
How to Enter the Mensuration (Semantic) Values

### ISSUE THREAD

**Issue by martha-thomae** [HISPAMUS/muret#162]
I would also suggest to let the user enter the `@modusmaior`, `@modusminor`,`@tempus`, and `@prolatio` values for each part (in the semantic interface, maybe?) because:
1. Sometimes there is no mensuration sign, but that doesn't mean there is no mensuration (there is an implicit relation between the different note levels)
2. Sometimes the mensuration sign does not match the interpretation of the relation between the notes (the values of modus minor, tempus, and prolatio).

So, MuRET can encode the mensuration sign recognized (using @mensur.sign, @mensur.dot, etc.) and the mensuration values are provided by the user (and encoded using `@modusmaior`, `@modusminor`,`@tempus`, and `@prolatio`).

**Comment by martha-thomae** [comment]
I was thinking: you don't only have to include the semantics of a mensuration sign (i.e., the values of `@modusmaior`,`@modusminor`,`@tempus`, and `@prolatio`) only at the beginning of the voice, but also at any place where a new mensuration sign appears (which can be mid-voice).

So, a possible solution could be to include this interpretation in the semantic interface. You have already the sign recognized during the agnostic step (`*met(C)`) in the ****smens** table, and you can add to it a series of four numbers indicating the values of the maximodus, modus minor, tempus, and prolatio, respectively. This would mean to change `*met(C)` into for example `*met(C)_2222` (for imperfect mensuration at all four note levels).

As another example: you have `*met(O3)` in the ****smens** table, you can change its manual encoding into `*met(O3_2332)` for imperfect maximodus, perfect modus minor, perfect tempus, and minor prolatio.

**Comment by davidrizo** [comment]
Thank you @martha-thomae for the proposal. I've chosen the `*met(C)_2222` syntax. It's now working in development until it's deployed to production environment

**Comment by martha-thomae** [comment]
Thank you!
