### ISSUE TITLE
Issues with clef elements (in parts)

### ISSUE THREAD

**Issue by martha-thomae** [HISPAMUS/muret#172]
- [x] All `<clef>` elements point to the same `<zone>` element in their `@facs` attribute. Each `<clef>` should point to the appropriate zone (the one for the clef in that system). This will finish resolving issue https://github.com/HISPAMUS/muret/issues/72#issue-526101500

- [x] These `<clef>` elements within `<layer>` have (two) extra indentations

- [ ] Remove the `<clef>` in `<staffDef>`, it is already in the `<layer>` following the `<pb>` and `<sb>` elements at the beginning of the voice.

**Comment by martha-thomae** [comment]
Regarding the last checkbox:

> * [ ]  Remove the `<clef>` in `<staffDef>`, it is already in the `<layer>` following the `<pb>` and `<sb>` elements at the beginning of the voice.

It is true that the clef could be encoded within `<staffDef>` instead. But I was wondering... so, **each system** at its **beginning** is the one that contains the clef. 

Differently from the mensuration symbol (which is defined only once for the whole voice—unless there is a change in mensuration, of course), the clef is defined for each system. So I am under the impression that it might be more appropriate to locate each clef after the `<sb>` tag it is related to. Right now, this is how we are handling them in the MP-Editor, and at the moment of converting the parts into a score, all these `<clef>` elements in the layer get deleted—except when they indicate a change in clef—and "the clef" of the voice gets moved into `<staffDef>`.

**Comment by davidrizo** [comment]
I didn't notice this check box :(

Anyway, removing the clef inside staffDef has more implications, e.g. the position of accidentals in the key signature. I think it's much better to encode clef and key information in staffDef

**Comment by martha-thomae** [comment]
Hmmm, that is complement true. Ok. I will add support for dealing with both types of definition for the "first clef" within the score editor.

**Comment by martha-thomae** [comment]
So, thinking about it a bit more, shouldn't both the `<clef>` and the `<keySig>` be encoded within the `<layer>` following the `<sb/>` tag, therefore, showing the clef and key signature included at the beginning of that system?

Differently from the mensuration sign, both clefs and key signatures appear at the beginning of each system. So, **for the `<parts>`-based MEI**, shouldn't these (`<clef>` and `<keySig>`) be included after each `<sb/>`?

**Comment by davidrizo** [comment]
Yes, we should use individual clefs after the `<pb>` in facsimile mode because they must be linked to the graphical zone

**Comment by davidrizo** [comment]
Just for the record, we've reached (with @martha-thomae) this agreement:
- clef and key signatures are moved to the layer because they are usually repeated for each new system break
- mensuration signs are usually established in the beginning of the work, and they don't need to be written after each new break, then, we maintain them inside the `staffDef` element
