### ISSUE TITLE
Allow for exporting a Parts MEI file with Un-Intepreted Rhythm

### ISSUE THREAD

**Issue by martha-thomae** [HISPAMUS/muret#173]
Allow for exporting **parts-based** MEI files in two flavours:

- With the attributes that encode the _interpretation of note durational values_ (either using `@num` and `@numbase` or using `@dur.quality`) and the _interpretation of the dot's functionality_ (using `@form`). **This is what is exported now.**

- Without these attributes. It is like a semi-semantic file. It has pitch values (which the agnostic lacks), but it doesn't have any rhythmic interpretation (neither for notes nor dots). **This is the one that will be used as input for the Measuring Polyphony score editor.**

**Comment by davidrizo** [comment]
A new button "Export Measuring Polyphony" is added that omits the dur.quality, num.* for notes and rests, and the dot type.
