### ISSUE TITLE
Add initial 'pb' element to all voices (in Parts MEI)

### ISSUE THREAD

**Issue by martha-thomae** [HISPAMUS/muret#176]
Some voices don't have a `<pb>` element to point to the folio where that voice is found. I would add `<pb>` at the beginning of **all** voices (the first child of their `<layer>` element) so that the voice reference the page where it is find. Otherwise, for someone not looking at the manuscript, there is no way to know where (in which folio) this voice is contained.

The use of `<pb>` at the beginning of **each** voice will solve this since `<pb>` points to the `<surface>` element that contains the information of the folio (including the coordinates of the corners of the page in its `@ulx`, `@uly`, `@lrx`, `@lry` attributes, and the actual image in the `@target` attribute of its `<graphic>` child  element).

**Comment by davidrizo** [comment]
I think we cannot add `<pb>` in all `<layer>` to reference the folio they belong, just the ones that are the first in the page, as `<pb>` stands for "page beginning". For knowing which folio they belong, the user must look for the last `pb` of the voice's context.

We can add the reference to the surface using the `@facs` attribute of `<layer>`

**Comment by martha-thomae** [comment]
I think layer might not be the right element for this. One voice is distributed over multiple pages, because a piece has page turns. Within layer we need multiple pb elements to indicate when a new page behind for that voice. You are indicating the page begin for that one voice.

**Comment by davidrizo** [comment]
Other option is to add the `<pb>` that includes the attribute `@sameas` that specifies which page beginning is being duplicated

**Comment by davidrizo** [comment]
A good example is the attached image. The fifth staff belongs to new voice.
<img width="267" alt="image" src="https://user-images.githubusercontent.com/10772049/90316304-89fa0480-df21-11ea-97eb-94b7fa0ec44b.png">

As it does not begin a new page, the `<pb>` element is missing:
```xml
<part label="Tenor" xml:id="part_468">
	<scoreDef xml:id="scoreDef_469">
		<staffGrp xml:id="staffGrp_470">
			<staffDef n="3" lines="5" label="Tenor" notationtype="mensural.white" xml:id="staffDef_471">
				<clef line="4" shape="C" facs="#symbol_175740" xml:id="clef_472"/>
					<mensur sign="C" modusmaior="2" modusminor="2" tempus="2" prolatio="2" facs="#symbol_175761" xml:id="mensur_473"/>
			</staffDef>
		</staffGrp>
	</scoreDef>
	<section xml:id="section_474">
		<staff n="3" xml:id="staff_475">
			<layer n="1" xml:id="layer_476">
				<sb xml:id="spb_477" facs="#region_31804"/>
				<rest xml:id="PART6_A14" facs="#symbol_175742" dur="longa" loc="4"/>
```

**Comment by martha-thomae** [comment]
> Other option is to add the `<pb>` that includes the attribute `@copyof` that specifies which page beginning is being duplicated

That doesn't sound bad. We could include then `<pb copyof="#some_xmlid" facs="#same_facs">`. Sounds good actually. What do you think?

**Comment by davidrizo** [comment]
I deleted the comment because I think we don't need it. It's exactly as you proposed. When exporting parts, each part is individual unrelated to other parts, so each page beginning must be explicitly encoded

**Comment by martha-thomae** [comment]
> I deleted the comment because I think we don't need it. It's exactly as you proposed. When exporting parts, each part is individual unrelated to other parts, so each page beginning must be explicitly encoded

I agree with this even more.
