### ISSUE TITLE
MEI facsimile export - invalid lrx in non ordered symbols

### ISSUE THREAD

**Issue by davidrizo** [HISPAMUS/muret#178]
When expanding the lrx in the facsimile MEI export (https://github.com/HISPAMUS/muret/issues/67), when two symbols are contiguous but not ordered in the database correctly, they don't take the correct width. We must order the symbols given their x and y before exporting.

<img width="802" alt="image" src="https://user-images.githubusercontent.com/10772049/90170258-0e247e80-dda0-11ea-8916-f9f1cb91bcf6.png">

**Comment by davidrizo** [comment]
We must also check the last symbol lrx takes the lrx from its bounding box

**Comment by martha-thomae** [comment]
[Palestrina_7MissaSineNomine_f31v.zip](https://github.com/HISPAMUS/muret/files/5070704/Palestrina_7MissaSineNomine_f31v.zip)

**Comment by davidrizo** [comment]
Corrected by sorting the symbols using their x and y coordinates rather than their order of insertion in the database.
Currently, the dot cannot have a specific `@facs` as it's associated to a note.

**Comment by martha-thomae** [comment]
> Currently, the dot cannot have a specific `@facs` as it's associated to a note.

Sorry, I am not understanding this part. How is the `<dot>` associated to a note? It is not an attribute of the note nor its child. Instead, it is an individual element in the same hierarchal level of the note. So, why does `<dot>` can't have its own `@facs` attribute? After all, it also has a `<zone>` element for it (which is not the same as the `<zone>` of the "dotted" note). Am I missing something here?

**Comment by davidrizo** [comment]
In the current library, dots are an attribute of the note. In next versions it will be possible. I'll leave the issue open for this fact

**Comment by martha-thomae** [comment]
> In the current library, dots are an attribute of the note. In next versions it will be possible. I'll leave the issue open for this fact

Really? But I saw that they are exported as individual elements in the output MEI file (I see `<dot>` being used as sibling following the `<note>` that they do follow in the manuscript)... obviously I am missing something, sorry.

**Comment by martha-thomae** [comment]
BTW, we can leave this issue https://github.com/HISPAMUS/muret/issues/66 open instead. Since the current one is more related to `@lrx`.
