### ISSUE TITLE
Semantic: The dots are not shown

### ISSUE THREAD

**Issue by martha-thomae** [HISPAMUS/muret#19]
After clicking on "convert from agnostic" the **mens generated does contain the dots, but they are not rendered.

**Comment by davidrizo** [comment]
In "semantic" **mens we are using ':' for division dots and '.' for augmentation dots. Regular **mens uses ':' for both of them

**Comment by martha-thomae** [comment]
Hi David,
Can you look at page 1v staff 3. There are dots of addition there, and they are encoded in the **mens, but they are not rendered.
