### ISSUE TITLE
Make accidental encoding and rendering consistent with **mens

### ISSUE THREAD

**Issue by martha-thomae** [HISPAMUS/muret#192]
In **mens, accidentals are only rendered when they are explicitly present in the encoding (see right side of screenshot).
The screenshot shows the same encoding in both MuRET and Verovio Humdrum Viewer. In MuRET the Uf (red circle) is rendered with a natural accidental (see the Verovio rendering) despite having no accidental in the encoding. MuRET also converts the `Uf` into an MEI element with an `@accid="n"` when, again, this accidental is not present in the source (see second screenshot).

![image](https://user-images.githubusercontent.com/13948831/113749280-7df0cc00-96d7-11eb-8adf-8dc441495cf3.png)

![image](https://user-images.githubusercontent.com/13948831/113749516-b98b9600-96d7-11eb-9f69-ab5be31d7d37.png)

The same encoding is provided to the VHV, and no accidental is shown for that Uf note (and the MEI has no additional accidentals encoded).

It would be nice to follow the practice of **mens for this too. Because normally, accidentals that are not present in the source are encoded as editorial accidentals (not regular accidentals as MuRET is doing right now).

**Comment by martha-thomae** [comment]
Another effect of this same issue can be seen in the next screenshot:

![image](https://user-images.githubusercontent.com/13948831/113749767-02dbe580-96d8-11eb-9a4e-577072dc850c.png)

Here the `Mff#` appears twice (symbol no. 3 with accidental no. 22, and later on in symbol no. 7 with accidental no. 23). Both notes have accidentals explicitly written in the original, but the accidental is only rendered in the first of the two notes (see the Verovio rendering in the screenshot). 

It would be nice to follow the practice of **mens and only encode and render the accidentals that appear explicitly in the source. If we want to add other editorial accidentals, we can always do that with the `yy` token from **mens.

**Comment by davidrizo** [comment]
Now, previous accidentals in mensural are never taken into account
