### ISSUE TITLE
Bug (semantic): custos are being rendered in the wrong place

### ISSUE THREAD

**Issue by martha-thomae** [HISPAMUS/muret#194]
Although custos are encoded correctly in the **smens encoding, they are getting rendered a few pitches above their encoded value. An example of this is shown in the following screenshot.

![image](https://user-images.githubusercontent.com/13948831/113750595-0885fb00-96d9-11eb-9ab1-db266a204b49.png)

**Comment by davidrizo** [comment]
The MEI encoding is correct:
<custos pname="c" oct="5" xml:id="custos_489"/>
We'll check whether it's Verovio who is wrongly engraving it

**Comment by davidrizo** [comment]
It's corrected in the last Verovio version

**Comment by mariaalfaroc** [comment]
There is a similar issue with agnostic. If you use the agnostic to semantic transducer, it places the custos one position below the agnostic one.

<img width="1417" alt="Captura de pantalla 2021-04-10 a las 0 23 53" src="https://user-images.githubusercontent.com/56754030/114246896-216e0500-9994-11eb-89bb-6eb00a6eccb6.png">

**Comment by davidrizo** [comment]
The font is not aligned. The correct alignment is the one shown in the semantic view. We'll correct it
