### ISSUE TITLE
Allow for encoding accidentals in custos

### ISSUE THREAD

**Issue by martha-thomae** [HISPAMUS/muret#195]
Currently, one cannot encode accidentals in custos. But I think this option is already available in MEI.

![image](https://user-images.githubusercontent.com/13948831/113750926-5c90df80-96d9-11eb-8afb-2a350a520f4f.png)

![image](https://user-images.githubusercontent.com/13948831/113750938-5f8bd000-96d9-11eb-812c-d4ddfc74efe0.png)

**Comment by davidrizo** [comment]
We've added to the translation process. Currently Verovio is not correctly rendering it:
https://github.com/rism-digital/verovio/issues/2128

**Comment by davidrizo** [comment]
Implemented in Verovio with https://github.com/rism-digital/verovio/pull/2133/commits/8cc69c76cf0e2be6a459822c32c8f92ad6ad7d48

**Comment by davidrizo** [comment]
Waiting for the next release of Verovio to be included here

**Comment by davidrizo** [comment]
Using local compilation of toolkit
