### ISSUE TITLE
(Bug) Unable to convert semibreve rest on fifth staff line to semantic

### ISSUE THREAD

**Issue by mariaalfaroc** [HISPAMUS/muret#204]
Unable to convert semibreve rest on fifth staff line to semantic. It raises the following error: mismatched input '6' expecting {1, 2, 3, 4, 5}.

<img width="1398" alt="semibreverest" src="https://user-images.githubusercontent.com/56754030/114224571-87956080-9971-11eb-8733-314af6c5e583.png">

Try to manually classify a semibreve rest and place it on the fifth staff line and then convert it to semantic. It will give you the error described in the image above.

**Comment by davidrizo** [comment]
The translation of semibrevis, seminima, and fusa rests into MEI were wrong
