### ISSUE TITLE
Wrong name for 'symbol recognition' button

### ISSUE THREAD

**Issue by martha-thomae** [HISPAMUS/muret#219]
**Describe the bug**
The button to execute the symbol recognition process in a staff has the wrong name "execute document analysis"

![Screen Shot 2021-05-24 at 1 03 02 PM copy](https://user-images.githubusercontent.com/13948831/119383099-f19f6600-bc90-11eb-877b-c1fd258881f9.png)

**Comment by davidrizo** [comment]
Thanks :)
