### ISSUE TITLE
Semantic: ligatures not shown

### ISSUE THREAD

**Issue by martha-thomae** [HISPAMUS/muret#22]
I am entering the ligatures by hand in the **mens, but they are not rendered.

**Comment by davidrizo** [comment]
Added. Cannot mix ligature types yet (recta and obliqua). Recta ligature are encoded with [ ... ], and obliqua ligature with <...>.
Even though Verovio does not render yet the obliqua, and always render them as recta, they should be correctly encoded as recta ([) and obliqua (<)
