### ISSUE TITLE
Small issues in agnostic to semantic translation

### ISSUE THREAD

**Issue by martha-thomae** [HISPAMUS/muret#226]
## Summary of issues when going from agnostic to semantic
- [ ] Rests that lie on the third line of the staff never get their position in the semantic encoding. This happens regardless of the type of rest, so it happens for all semiminima / minima / semibrevis / brevis rests in the third line. See screenshots below.
- [ ] Some semiminimas' (quarter notes') stem direction does not correspond to the one of their agnostic encoding. I have seen this in both stem directions (up/down). See screenshots below.

The first issue is more important than the second one. The first issue can affect the perfect grouping of notes.

### Rests:

![rest_in_third_line](https://user-images.githubusercontent.com/13948831/125518139-ac10c245-c659-44a5-aaf7-439eef6a62d4.png)

![rest_in_third_line_2](https://user-images.githubusercontent.com/13948831/125518617-065d162e-dec0-4e71-b6ee-9f228839982e.png)

### Stems:

![agnostic and semantic stem](https://user-images.githubusercontent.com/13948831/125518154-7d08f330-d54b-4316-ba40-b53c4e05690b.png)

![stem direction 2](https://user-images.githubusercontent.com/13948831/125518752-146d56b0-0e7f-46cc-8eb0-738dfc4773fb.png)

**Comment by davidrizo** [comment]
@martha-thomae wrote: "Rests that lie on the third line of the staff never get their position in the semantic encoding. This happens regardless of the type of rest, so it happens for all semiminima / minima / semibrevis / brevis rests in the third line. See screenshots below."

This is done on purpose. The behavior is consistent with the stem direction. Just when the default rules to set the position of the rest are overridden (they don't lie on the third line), it's encoded. Should we change this behavior?

**Comment by davidrizo** [comment]
The stem related issue is corrected

**Comment by martha-thomae** [comment]
Oh. I didn’t know. I have some older semantic encodings that also included the 3rd line, that is why I got confused. No problem then! :)
