### ISSUE TITLE
Semantic: Stem direction does not match the one given in the agnostic representation

### ISSUE THREAD

**Issue by martha-thomae** [HISPAMUS/muret#23]
The stems of the notes seem to be automatically generated following the rule that notes that lie below or on the 3rd line have an upward stem and that notes above the 3rd line have a downward stem, rather than following the stem direction given in the agnostic representation.

This is why sometimes stems in L3 have the wrong direction, see image.

![Stem direction does note match agnostic representation](https://user-images.githubusercontent.com/13948831/59673765-2875c300-91c2-11e9-95b1-a3458e5aac07.png)

**Comment by davidrizo** [comment]
It seems Verovio is not following the rule

**Comment by davidrizo** [comment]
No rule is used for the stem direction, but the stem direction of the agnostic symbol
