### ISSUE TITLE
Cannot encode gestural and logical information of an accident at the same time

### ISSUE THREAD

**Issue by martha-thomae** [HISPAMUS/muret#251]
Sometimes the function of an accidental (its gestural interpretation) differs from the actual written accidental. For example, a sharp could be used to cancel the flat on a key signature (see the image below). In that case, one would like to encode both the written accidental (the sharp as `#X`) and its interpretation (`ny`) at the same time: `#Xny`. However, this cannot be done in MuRET. When I use the token `MB#Xny`, MuRET cannot parse it. Could this functionality be implemented (encoding both written and gestural accidentals at the same time)? Or is it already implemented and I am just not doing it correctly?

The equivalent of `#Xny` in MEI should be `<accid accid='s' accid.ges='n'/>`

![Screen Shot 2022-11-14 at 3 34 21 PM](https://user-images.githubusercontent.com/13948831/201760311-aafd1c5a-5ee3-48a8-ac47-d09cf901b62c.png)

**Comment by davidrizo** [comment]
We designed  `X#` for drawing a sharp but playing a natural. It's no need to add more information such as the `ny` in `MB#Xny`.

However, I'm exporting incorrectly to MEI:

```xml
<note xml:id="L17" dur="semiminima" pname="b" oct="3">
<accid accid.ges="f"/>
</note>
```

should be as @martha-thomae states:
```xml
<note xml:id="L17" dur="semiminima" pname="b" oct="3">
 <accid accid='s' accid.ges='n'/>
```

I'll correct it

**Comment by davidrizo** [comment]
Note the accidental must be `X#` (not `#X`)

**Comment by martha-thomae** [comment]
Thank you, @davidrizo! Will try that :)

**Comment by davidrizo** [comment]
The correct encoding is: ``sbX#``
