### ISSUE TITLE
Semantic: cannot add editorial accidentals

### ISSUE THREAD

**Issue by martha-thomae** [HISPAMUS/muret#26]
Adding editorial accidentals (using the **mens accidental qualifiers ```y```, ```yy```, ```Y```m and ```YY```) causes the "send semantic encoding" functionality to fail.

An example where an editorial accidental is needed is shown in the image below. The fusa F is encoded as ```Uf```, as shown in the manuscript. But due to its lack of accidental (and the previous Sb F#), Verovio renders a natural sign next to it. This is misleading because there is no accidental present in the manuscript. Probably this fusa F is an F# (given its proximity to the Sb F#), so it should be encoded as a ```Uf#yy``` rather than a ```Uf```. (If, on the other hand, it is actually a F natural, then it would be encoded as ```Ufnyy```). In any case, it should be encoded as an editorial accidental because it is not an actual accidental present in the manuscript. But encoding the editorial qualifier (either using ```Uf#yy``` or ```Ufnyy```) causes the "send semantic encoding" functionality to fail. 

![need for editorial accidentals](https://user-images.githubusercontent.com/13948831/59677441-257ed080-91ca-11e9-9f21-9e9a1b5ad2d3.png)

**Comment by davidrizo** [comment]
Done
