### ISSUE TITLE
Semantic: Rest position gets lost

### ISSUE THREAD

**Issue by martha-thomae** [HISPAMUS/muret#27]
**mens does not allow to encode the line in which the rest lies, therefore the translation from agnostic to semantic losses this information.

**Comment by davidrizo** [comment]
Corrected. 
The position is encoded using the same principle of the agnostic encoding, looking the closest line to the rest from the bottom). Then, a brevis that goes from line 3 to 5 (middle line to the top line), will be encoded as Lr_3
(we have avoided the R:v= encoding for being too verbose - then, this encoding may change in the future)
