### ISSUE TITLE
Semantic: notes in S0

### ISSUE THREAD

**Issue by martha-thomae** [HISPAMUS/muret#28]
Notes in S0 get encoded in **mens as being an octave below their actual position:

![Screen Shot 2019-06-18 at 1 22 56 PM](https://user-images.githubusercontent.com/13948831/59678385-93c49280-91cc-11e9-9966-37d894af39ad.png)
![Screen Shot 2019-06-18 at 1 23 45 PM](https://user-images.githubusercontent.com/13948831/59678386-93c49280-91cc-11e9-8291-d8a771564c8c.png)

**Comment by davidrizo** [comment]
Corrected
