### ISSUE TITLE
Semantic: Dots within ligatures are not rendered

### ISSUE THREAD

**Issue by martha-thomae** [HISPAMUS/muret#30]
While all dots are shown in the Verovio rendition of the semantic encoding, they do not show when they are part of a ligature.

See indices _4,5_ in the attached figure

![dots within ligatures](https://user-images.githubusercontent.com/13948831/62122621-689e8a00-b2c6-11e9-969e-ce321b916180.png)

**Comment by davidrizo** [comment]
Currently it seems MEI is not allowing to include <dot> elements inside ligature.
Besides, when used, verovio reports the error:
"[Warning] Element <dot> within <ligature> is not supported and will be ignored "

**Comment by davidrizo** [comment]
See Verovio issue
https://github.com/rism-ch/verovio/issues/846

**Comment by martha-thomae** [comment]
The issue has been fixed recently in Verovio. Would you mind updating it in MuRET as well, please?

**Comment by martha-thomae** [comment]
I guess it should work with both **smens encodings for dots:
- `S:A` (dot of division)
- `S.A` (dot of augmentation)
