### ISSUE TITLE
In all cases, separate the delete button (the trash icon) with a vertical separator. This action should be confirmed twice

### ISSUE THREAD

**Issue by davidrizo** [HISPAMUS/muret#39]
See crud-toolbar-component.ts

**Comment by antoniorv6** [comment]
Separators set between functionality regions: Zoom adjustment | Edition | Delete
![separators](https://user-images.githubusercontent.com/36246417/66900344-e8521000-effc-11e9-90bc-431e7b52a024.png)

Waiting for @davidrizo confirmation

**Comment by antoniorv6** [comment]
Improved hover interaction, moving this issue to Testing
