### ISSUE TITLE
Ask twice if the user wants to delete a region in agnostic. Highlight it cannot be undone. In general, improve the messages

### ISSUE THREAD

**Issue by davidrizo** [HISPAMUS/muret#40]
See crud-toolbar-component.ts

**Comment by antoniorv6** [comment]
General modal design improved.
Created a new component - ConfirmDialogWarningComponent (it only changes CSS attributes, but I consider to better have it aside of simple ConfirmDialogComponent) and implemented the method to dispatch it: showWarningConfirmation(title, message)
Reduced modal width with Bootstrap defaults and included the blackened background to emphasise the message.

Now user is asked twice if he wants to delete the agnostic region, just included a subscription that dispatches the action inside the first confirmation. Images pinned in this message to check the result.
![Modal1](https://user-images.githubusercontent.com/36246417/66823950-900d0680-ef47-11e9-8008-26ad9df94e31.png)
![Modal2](https://user-images.githubusercontent.com/36246417/66823955-91d6ca00-ef47-11e9-963c-bb7a64730d27.png)

Waiting for @davidrizo approval to push it. Moving to test
