### ISSUE TITLE
Keyboard shortcut

### ISSUE THREAD

**Issue by kuanji** [HISPAMUS/muret#58]
Make a new keyboard shortchut in order to choose the type of box do yo want to set.

**Comment by antoniorv6** [comment]
You mean a shortcut to avoid this step at Document Analysis?
![42c9514c075c133157dedf85a8048fe3](https://user-images.githubusercontent.com/36246417/67944430-c2bc2d80-fbdc-11e9-8a89-a99088d779f6.jpg)
Please, next time specify in which feature/page the change has to be implemented. If you don't know, just post a screenshot. It helps a lot to guide me :)

**Comment by antoniorv6** [comment]
Shortcut enabled. If you press B while you are in Adding Mode, it swaps to the next type of region.
