### ISSUE TITLE
Maintain selected staff when changing between agnostic and semantic

### ISSUE THREAD

**Issue by davidrizo** [HISPAMUS/muret#60]
When a region is selected in semantic or agnostic, if the mode (agnostic / semantic) is changed, it should be still selected

**Comment by antoniorv6** [comment]
Tracing Redux Actions and calls to the state. I found out that you dispatch an action called InitRegion to the store.
This wipes out the selected staff during the semantic analysis. Is this Action dispatching relevant? Commenting the line gives the desired effect.
