### ISSUE TITLE
Missing attributes corresponding to mensuration in the MEI file

### ISSUE THREAD

**Issue by martha-thomae** [HISPAMUS/muret#64]
The ```<staffDef>``` elements exported into the MEI file are **missing** the encoding of attributes related to mensuration: ```@modusmaior```, ```@modusminor```, ```@tempus```, and ```@prolatio```. If these attributes are not encoded, Verovio assigns them a ternary value by default (i.e., ```modusmaior='3' modusminor='3' tempus='3' prolatio='3'```). This is why the notes are not lining up even in pieces in duple meter, they need to include these attributes and all of them should be equal to ```'2'```.

**Comment by davidrizo** [comment]
The tempus and prolatio have been added. 
Rather than adding hidden barlines, that could lead us to a problem when encoding long notes that span two measures, we have used the options:
--page-width 60000  --no-justification

**Comment by martha-thomae** [comment]
Could you add `modusminor="2"` as well? Verovio won't render it correctly unless the three values of modus minor, tempus, and prolatio are present (this is why a few pieces are not lining up, once I add that, everything looks perfect).
