### ISSUE TITLE
MEI file: Error in the encoding of the dots of augmentation

### ISSUE THREAD

**Issue by martha-thomae** [HISPAMUS/muret#65]
Dots of augmentation are currently encoded as:
```
<note dots='1'/>
<dot form='aug'/>
```

They should be changed into:
```
<note num='2' numbase='3'/>
<dot form='aug'>
```

In other words, change the ```@dots='1'```(which is unnecessary given that the dot of augmentation is encoded in the next element) to ```@num='2' @numbase='3'```. This is to be consistent with the current guidelines of MEI (removing the ```dots='1'```) and also to encode the actual effect of the augmentation dot on the note (using ```@num='2' @numbase='3'```). 

This missing ```@num``` and ```@numbase``` attributes in the note, together with the mensuration issue #64, are affecting the voice alignment.

**Comment by martha-thomae** [comment]
Here I am including some files to give an example of the need to solve the issues #64 and #65 so that Verovio renders the notes lined up:

* **FIRST:** The ```export_229.mei``` is the original (score) MEI file returned by MuRET. As you will see in Verovio, the notes won't lined-up. 
* **SECOND:** In the ```preprocessing.mei``` file, a few things were changed so that Verovio would interpret the duration of the notes correctly:
1. I encoded the mensuration values in the ```<staffDef>``` elements (```@modusmaior```, ```@modusminor```, ```@tempus```, and ```@prolatio```), as pointed out in issue #64 
2. And I encoded the effect of the dots of augmentation (with the ```@num``` and ```@numbase``` ratio) as indicated in this issue (#65)
* **THIRD:** The last file is the ```barred.mei```. Here I added barlines because Verovio is able to cut the piece into "pages" if the barlines at the different voices coincide (if you zoom in you will see that the piece cuts into several pages instead of squishing all the notes into a single page). We could think of using invisible barlines so that Verovio won't squish the notes together.

[22_Lumen_ad_revelationem.zip](https://github.com/HISPAMUS/muret/files/3848352/22_Lumen_ad_revelationem.zip)

**Comment by davidrizo** [comment]
The example files still contain the attribute @dot. Is that correct?
<note xml:id="A25" facs="#symbol_130105" dur="minima" **dots="1"** pname="g" oct="5" num="2" numbase="3" />
<dot xml:id="m-227678d0-fbfd-4557-b5f6-7b1e12fecf2a" form="aug" />

Should be?
<note xml:id="A25" facs="#symbol_130105" dur="minima" pname="g" oct="5" num="2" numbase="3" />
<dot xml:id="m-227678d0-fbfd-4557-b5f6-7b1e12fecf2a" form="aug" />
