### ISSUE TITLE
MEI file (facsimile): Expanding the bounding boxes of the symbols

### ISSUE THREAD

**Issue by martha-thomae** [HISPAMUS/muret#67]
Instead of having the bounding box width fixed (in this case to 25 pixels), could we expand the bounding boxes so that they finish where the next symbol begins?

This would mean making the ```@lrx``` attribute of a given element (which could be a ```<note>```, ```<rest>```, ```<ligature>```, or ```<dot>```) be the same as the ```@ulx``` attribute of the following element. Except for the last element in the staff (which probably would be the ```<custos>```), in which case the value of its ```@lrx``` attribute could be the same as the ```@lrx``` attribute of the ```<staff>``` bounding box.

**Comment by davidrizo** [comment]
Done using @martha-thomae proposal
