### ISSUE TITLE
Notify registered users of new versions

### ISSUE THREAD

**Issue by davidrizo** [HISPAMUS/muret#79]
When a new version of MuRET is uploaded, we should notify all registered users by send them a mail

**Comment by antoniorv6** [comment]
Server watchdog notifies if it finds a new MuRET version.
The procceeding is that we will have to store two files in the server. One with the current version of MuRET (which is automatically updated by the program). And other with the patch notes, which we will have to provide every time we make a major upgrade. When booted, the server watchdog seeks for a new version and if it finds it, emails all the registered users.
