### ISSUE TITLE
Agnostic region resizing

### ISSUE THREAD

**Issue by davidrizo** [HISPAMUS/muret#82]
Agnostic: when the region is very short, it should be resized to fit the whole browser width

**Comment by antoniorv6** [comment]
https://muret.dlsi.ua.es/muret/#/agnosticrepresentation/2283

**Comment by davidrizo** [comment]
It does not work correctly on two page manuscripts: e.g. PRUEBAS collection, 12609.JPG > etiquetado > first page > first staff. When trying to create the bounding box for the clef we get:
![image](https://user-images.githubusercontent.com/10772049/76159440-c595d480-6120-11ea-86d7-4146932a35f6.png)
